name: "Build project"

env:
  GODOT_VERSION: "4.2.1"

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  android:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.0.x

      - name: Cache downloaded godot
        id: cache-godot
        uses: actions/cache@v4
        with:
          path: ./Godot_v${{ env.GODOT_VERSION }}-stable_mono_linux_x86_64/
          key: ${{ runner.os }}-${{ env.GODOT_VERSION }}-godot

      - name: Initialize Godot
        if: steps.cache-godot.outputs.cache-hit != 'true'
        run: |
          curl -f -L -o godot.zip https://github.com/godotengine/godot/releases/download/${GODOT_VERSION}-stable/Godot_v${GODOT_VERSION}-stable_mono_linux_x86_64.zip
          unzip ./godot.zip

      - name: Cache downloaded templates
        id: cache-godot-templates
        uses: actions/cache@v4
        with:
          path: /root/.local/share/godot/export_templates/${{ env.GODOT_VERSION }}.stable.mono
          key: ${{ runner.os }}${{ env.GODOT_VERSION }}-templates

      - name: Initialize export templates
        if: steps.cache-godot-templates.outputs.cache-hit != 'true'
        run: |
          curl -f -L -o export_templates.zip https://github.com/godotengine/godot/releases/download/${GODOT_VERSION}-stable/Godot_v${GODOT_VERSION}-stable_mono_export_templates.tpz
          unzip ./export_templates.zip
          mkdir -p ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable.mono
          mv ./templates/* ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable.mono

      - name: Build project
        run: |
          mkdir -p ./build
          ./Godot_v${GODOT_VERSION}-stable_mono_linux_x86_64/Godot_v${GODOT_VERSION}-stable_mono_linux.x86_64 --headless --verbose --export-release "Linux/X11" "./build/stacking"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux
          path: build
