name: "Build project"

env:
  GODOT_VERSION: "4.2.1-stable"

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Initialize Godot
        run:
          wget https://github.com/godotengine/godot/releases/download/${GODOT_VERSION}/Godot_${GODOT_VERSION}_mono_linux.x86_64.zip -o godot.zip
          unzip ./godot.zip
          mv ./Godot_v${GODOT_VERSION}_mono_linux.x86_64/Godot_v${GODOT_VERSION}-stable_mono_x11.64 ~/.local/bin/godot

      - name: Initialize export templates
        run:
          wget https://github.com/godotengine/godot/releases/download/${GODOT_VERSION}/Godot_${GODOT_VERSION}_mono_export_templates.tpz -o export_templates.zip
          unzip ./godot-templates.zip
          mkdir -p ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
          mv ./templates/* ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable

      - name: Build project
        run: godot --export "Android" "builds/mygame.apk"
